### ISSUE TITLE
Does not show romaji properly in Ubuntu 20

### ISSUE THREAD

**Issue by zlin888** [skywind3000/KanaQuiz#1]
![Screenshot from 2021-12-23 18-45-02](https://user-images.githubusercontent.com/45032494/147300055-0a267618-31d9-4aee-9a86-22d1a220f08c.png)

**Comment by skywind3000** [comment]
Same color with the background ?? adjust the terminal palette ?

**Comment by skywind3000** [comment]
or modify  the code, pick another color for romaji

**Comment by A0nameless0man** [comment]
In author‘s code，color is stored in a byte
```python
foreground = color & 7
background = (color >> 4) & 7
bold = color & 8
```
however,color of romaji was defaulted to 8,means foreground and background color are both 0(black),you can fix it by replace like this：
![image](https://user-images.githubusercontent.com/17798917/147399800-a8027791-8ad7-40e9-bfde-193903bb338c.png)

**Comment by zlin888** [comment]
Thanks! Not quite sure what happened. But I followed @A0nameless0man instruction and randomly choose a number. Now it shows properly.
